import {
  SiAdobexd,
  SiAmazonaws,
  SiAngular,
  SiCss3,
  SiExpress,
  SiFigma,
  SiGooglecloud,
  SiGraphql,
  SiHtml5,
  SiInvision,
  SiJavascript,
  SiJest,
  SiMongodb,
  SiMongoose,
  SiNextdotjs,
  SiNodedotjs,
  SiPostgresql,
  SiReact,
  SiRedux,
  SiSass,
  SiSequelize,
  SiSketch,
  SiTailwindcss,
  SiTypescript,
} from "react-icons/si";

export const about = {
  me: "Sebastian Sanchis",
  logo: "/assets/work.svg",
  photo: "/assets/about_me-02.jpg",
  gitHub: "https://github.com/seba-sanchis",
  linkedIn: "https://www.linkedin.com/in/sebastian-sanchis/",
  resume:
    "https://drive.google.com/file/d/1evRqVme7rHrO82Rz5cy8Is3M0IfoVDFG/view?usp=share_link",
};

export const projects = [
  {
    title: "Blog",
    description:
      "Effortless content delivery with Hygraph, a powerful Headless CMS for sharing insightful articles and engaging stories.",
    image: "/assets/project_blog.png",
    technologies: "GraphQL, NextJS, Tailwind CSS.",
    source: "https://github.com/seba-sanchis/blog",
    visit: "https://blog.sebastiansanchis.com/",
    id: 0,
  },
  {
    title: "CMS",
    description:
      "Dynamic app syncing with E-commerce. Intuitive interface for sales metrics, content and inventory management.",
    image: "/assets/project_cms.png",
    technologies: "Angular, Sass, Typescript.",
    source: "https://github.com/seba-sanchis/cms",
    visit: "https://cms.sebastiansanchis.com/",
    id: 1,
  },
  {
    title: "E-commerce",
    description:
      "Facilitates cart management, seamless checkout, and receives updated content from the connected CMS.",
    image: "/assets/project_e-commerce.png",
    technologies: "NextJS, Tailwind CSS, Typescript.",
    source: "https://github.com/seba-sanchis/e-commerce",
    visit: "https://e-commerce.sebastiansanchis.com/",
    id: 2,
  },
];

export const stack = [
  { title: "Frontend" },
  { title: "Backend" },
  { title: "UI/UX" },
];

export const skills = [
  { stack: "Frontend", icon: SiAngular, technology: "Angular" },
  { stack: "Frontend", icon: SiCss3, technology: "CSS" },
  { stack: "Frontend", icon: SiGraphql, technology: "GraphQL" },
  { stack: "Frontend", icon: SiHtml5, technology: "HTML" },
  { stack: "Frontend", icon: SiJavascript, technology: "JavaScript" },
  { stack: "Frontend", icon: SiJest, technology: "Jest" },
  { stack: "Frontend", icon: SiNextdotjs, technology: "NextJS" },
  { stack: "Frontend", icon: SiReact, technology: "React" },
  { stack: "Frontend", icon: SiRedux, technology: "Redux" },
  { stack: "Frontend", icon: SiSass, technology: "Sass" },
  { stack: "Frontend", icon: SiTailwindcss, technology: "TailwindCSS" },
  { stack: "Frontend", icon: SiTypescript, technology: "Typescript" },
  { stack: "Backend", icon: SiAmazonaws, technology: "AWS" },
  { stack: "Backend", icon: SiExpress, technology: "Express" },
  { stack: "Backend", icon: SiGooglecloud, technology: "GCP" },
  { stack: "Backend", icon: SiMongodb, technology: "MongoDB" },
  { stack: "Backend", icon: SiMongoose, technology: "Mongoose" },
  { stack: "Backend", icon: SiNodedotjs, technology: "Node" },
  { stack: "Backend", icon: SiPostgresql, technology: "PostgreSQL" },
  { stack: "Backend", icon: SiSequelize, technology: "Sequelize" },
  { stack: "UI/UX", icon: SiAdobexd, technology: "Adobe Xd" },
  { stack: "UI/UX", icon: SiFigma, technology: "Figma" },
  { stack: "UI/UX", icon: SiInvision, technology: "Invision" },
  { stack: "UI/UX", icon: SiSketch, technology: "Sketch" },
];

export const experience = [
  {
    startDate: "Sep 2017",
    endDate: "Aug 2023",
    company: "Vulcano S.A.",
    description: "Consumer Goods",
    position: "Project Web Manager",
    image: "/assets/experience_vulcano.jpg",
    link: "http://vulcano-sa.com",
    skill: [
      "Lead a team in a good work environment.",
      "Develop short and long term roadmaps aligned to the company's business plans.",
      "Plan the tasks of the team, coordinating with different areas and giving the necessary visibility to the competent people.",
      "Organize the working group to meet the objectives in a timely manner.",
      "Collaborate in the generation of the new website together with development, design and writing professionals.",
      "Participate in the complete development cycle of the website and guarantee excellence in execution.",
    ],
  },
];

export const education = [
  {
    startDate: "Nov 2022",
    endDate: "Nov 2022",
    school: "Digital House",
    description: "Educational institution",
    study: "SOLID",
    image: "/assets/education_digital-house.jpg",
    link: "https://g.co/kgs/cZRwaL",
    skill: [
      "SRP: Single Responsibility Principle",
      "OCP: Open/Closed Principle",
      "LSP: Liskov Substitution Principle",
      "ISP: Interface Segregation Principle",
      "DI: Dependency Inversion",
    ],
  },
  {
    startDate: "Nov 2022",
    endDate: "Nov 2022",
    school: "Digital House",
    description: "Educational institution",
    study: "Software Design Patterns",
    image: "/assets/education_digital-house.jpg",
    link: "https://g.co/kgs/cZRwaL",
    skill: [
      "Pattern Types: Creational, Structural, and Behavioral.",
      "Creational Patterns: Singleton, Builder, Factory.",
      "Structural Patterns: Adapter, Facade, Decorator.",
      "Behavior Patterns: Strategy, Command, Observer.",
    ],
  },
  {
    startDate: "Nov 2022",
    endDate: "Nov 2022",
    school: "Digital House",
    description: "Educational institution",
    study: "Object-Oriented Programming (OOP)",
    image: "/assets/education_digital-house.jpg",
    link: "https://g.co/kgs/cZRwaL",
    skill: [
      "OOP with JavaScript and TypeScript.",
      "Pillars of OOP: Encapsulation, Inheritance, Polymorphism, Abstraction.",
      "Interfaces",
    ],
  },
  {
    startDate: "Oct 2022",
    endDate: "Oct 2022",
    school: "Digital House",
    description: "Educational institution",
    study: "Deployment with Amazon Web Services (AWS)",
    image: "/assets/education_digital-house.jpg",
    link: "https://g.co/kgs/cZRwaL",
    skill: [
      "Client–server model",
      "Transmission Control Protocol (TCP)",
      "Internet Protocol Suite (TCP/IP)",
      "Hypertext Transfer Protocol (HTTP)",
      "Hypertext Transfer Protocol Secure (HTTPS)",
      "Domain",
      "Hosting",
      "AWS IAM",
      "AWS EC2",
      "AWS Load Balancer",
      "AWS Security Groups",
      "AWS RDS",
      "AWS S3",
    ],
  },
  {
    startDate: "Sep 2022",
    endDate: "Sep 2022",
    school: "Digital House",
    description: "Educational institution",
    study: "Test-Driven Development (TDD)",
    image: "/assets/education_digital-house.jpg",
    link: "https://g.co/kgs/cZRwaL",
    skill: [
      "Automated testing",
      "Testing in Node.js with Jest",
      "Test-driven development in Node.js",
      "Coding Katas",
    ],
  },
  {
    startDate: "Aug 2022",
    endDate: "Sep 2022",
    school: "Meta",
    description: "Technology company",
    study: "Front-End Development",
    image: "/assets/education_meta.jpg",
    link: "https://g.co/kgs/u63y1h",
    skill: [
      "Describe the web developer job role.",
      "Distinguish between front-end, back-end, and full-stack developers.",
      "Explain how data moves through the internet.",
      "Describe the technologies that underpin the internet.",
      "Use HTML to create a simple web page.",
      "Use CSS to define style of a simple web page.",
      "Outline the concepts that exist in most UI frameworks using bootstrap as an example to directly reference common practice.",
      "Use the Bootstrap CSS Framework to create webpages.",
      "Leverage bootstrap documentation to reproduce and modify CSS components.",
      "Use bootstrap themes.",
      "Describe the basics of react in relation to other frameworks and web technologies.",
    ],
  },
  {
    startDate: "Jul 2022",
    endDate: "Aug 2022",
    school: "Google",
    description: "Technology company",
    study: "Web Development",
    image: "/assets/education_google.png",
    link: "https://g.co/kgs/RUqd6f",
    skill: [
      "Web history.",
      "How the website works.",
      "How to write a web page.",
      "How a website is published.",
      "How to write a well-structured web page.",
      "How to define the presentation of a web page.",
      "How the presentation of the elements of a web page is defined.",
      "How to make a web page.",
      "How do you make a website successful?.",
    ],
  },
  {
    startDate: "Aug 2021",
    endDate: "Feb 2022",
    school: "Digital House",
    description: "Educational institution",
    study: "Full Stack Web Developer",
    image: "/assets/education_digital-house.jpg",
    link: "https://g.co/kgs/cZRwaL",
    skill: [
      "CSS",
      "Express.js",
      "Git",
      "GitHub",
      "HTML",
      "JavaScript",
      "JSON",
      "Model-View-Controller (MVC)",
      "MySQL",
      "Node.js",
      "React.js",
      "Representational State Transfer (REST)",
      "Scrum",
      "Sequelize.js",
      "SQL",
    ],
  },
];

export const contact = {
  image: "/assets/contact_email.png",
};
